### ISSUE TITLE
App Dependencies

### ISSUE THREAD

**Issue by ds0nt** [metamaps/metamaps_gen002#373]
I'm setting up my dev instance and working out a solution for docker.  https://github.com/metamaps/metamaps_gen002/issues/372

 while I go I would like to pave the road as much as possible. I see that there is a phantomjs job, postgres db, redis, and nodejs. It's not very straight forward, especially when it comes to development environments, deployment, and scalability. [12 Factor App - Backing Services] (http://12factor.net/backing-services) explains about it.

in the end I think it would be excellent to separate the git repositories, and dockerfiles.

Keep the metamaps repository just as the webserver code, and try and distance it with dependencies.

PhantomJS is just being used as a job, right? =]

This will go along great with Docker. I can make a process that will make it simple to launch the worker, db, redis, webserver, and socketserver independently.

p.s. gonna update the ubuntu install docs along the way. They didn't tell me what the purpose of each dependency was, and what they were for =]

p.s. the contributor agreement link here is dead on the [Contributor License Agreement](https://github.com/metamaps/metamaps_gen002/blob/master/CONTRIBUTING.md#contributor-license-agreement)

- [x] Move database config into environment variable
- [ ] Remove redis
- [x] Remove phantomjs
- [ ] Consider moving realtime server into a separate repo

**Comment by devvmh** [comment]
This is a great idea

**Comment by devvmh** [comment]
Phantomjs is gone now, I think.

What do we even use redis for? devise? I grepped the codebase and only found it in the Gemfile and documentation.

I hear the argument for moving realtime into a separate repo, but I think for now it's much simpler to keep it together. Also, we have no plans to make the realtime server API stable, so it is tightly coupled to the ruby backend right now.

**Comment by Connoropolous** [comment]
Yeah phantomjs is gone
