### ISSUE TITLE
Update to Ruby 2-1-5

### ISSUE THREAD

**Issue by ds0nt** [metamaps/metamaps_gen002#374]
I think updating the gem file should be harmless: https://www.ruby-lang.org/en/news/2014/11/13/ruby-2-1-5-is-released/

yes, no? I might as well because I was unable to find a rails dockerfile (#372) that is under 800mb... and I already downloaded the new one =]

**Comment by devvmh** [comment]
@ds0nt Feel free to update the Gemfile on a local development instance, that's always fine. If we update ruby on the develop or master branch we'll just do some testing first, and that doesn't need to hold up your development :D

We might not even ever update ruby to 2.1.5, some new version will probably come out before we need to. No sense in doing more work on the production servers than we have to
