### ISSUE TITLE
Merge Peices of Metamind

### ISSUE THREAD

**Issue by ds0nt** [metamaps/metamaps_gen002#375]
Hey, this is the mind-mapping web app I've been building. Make sure to give it a look, and see what you like and dislike. I hope we can cross-implement some features =]

[Metamind](http://130.211.170.58/)
[Mind Map](http://130.211.170.58/app/graph/2fc36be9-1f17-4b31-a86f-098815bb8a25)

p.s. coincidentally named 'metamaps' and 'metamind', which lead me to discover this, but I will change it's name :).

**Comment by devvmh** [comment]
@ds0nt are you still interested in merging bits of metamind? I know it's over a year later, but I can't load the app

**Comment by ds0nt** [comment]
Hey Devin, What's up?

**Comment by devvmh** [comment]
I was wondering what the status if metamind/this ticket was. I never saw metamind before, so I'm interested

**Comment by ds0nt** [comment]
I've renamed it to Forky. And I've started actively developing it as of two
months ago. Complete rewrite, Golang backend, React (with minimal
dependencies) frontend. :) give me a minute and I'll deploy it. ;)

**Comment by ds0nt** [comment]
take a look at http://forky.io

**Comment by ds0nt** [comment]
and don't click on the broken pricing button :p

**Comment by devvmh** [comment]
Looks cool! Im guessing that means i can safely close this ticket. 

I would love to rewrite our frontend in react. Ive been trying to splice tests onto our code to improve the maintainability, and react is good for that! The dream would be to have loosely voupled modules like "map view" "chat room" and "topic view" that could be recombined and are linked to rails via the api and viaeach other with socket.io. 

For now its a dream haha, so i wish you the best with your beautiful, still-new codebase :D

**Comment by ds0nt** [comment]
Thanks :)
