### ISSUE TITLE
Export map images with highlighted synapses

### ISSUE THREAD

**Issue by poietic** [metamaps/metamaps_gen002#393]
there's already been 3 people who have asked for this, two of them from within the uservoice ticket queue. without it, the export feature's really not that useful - they're defaulting back to taking screenshots.

**Comment by Connoropolous** [comment]
I'm working on this one, making a really simple way to choose between capturing current view, and capturing whole map :)

**Comment by Connoropolous** [comment]
I'm working on this one, making a really simple way to choose between capturing current view, and capturing whole map :)

**Comment by Connoropolous** [comment]
I've almost got this done! I'll submit a PR soon and push it to staging to show y'all. @poietic there'll be at least a small image asset needed

**Comment by poietic** [comment]
yep! i'll check it out as soon as its on staging, just let me know!
