### ISSUE TITLE
if title of topic is blank, cannot edit it within topic card title edit area

### ISSUE THREAD

**Issue by poietic** [metamaps/metamaps_gen002#399]
...have to increase the size of the div in order to edit it currently.

**Comment by devvmh** [comment]
OK it looks like someone fixed this. I think it might have been me, but I can't find the exact commit or the mechanism. Anyways, you can't create blank topics, and if you edit a topic to make the title blank, it changes to a "-". I've just updated 28 blank topics on metamaps.cc to have the -, so this is solved.
