### ISSUE TITLE
Generate blank synapse even if user doesn't hit Enter for faster data entry

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps_gen002#403]
I tried making a map today, and I just wanted a bunch of blank synapses. I didn't want to label them. I think it was clear from the topics that there was a relationship, and it didn't matter how it was labelled

If I dragged an arrow from one topic to the other, and then clicked on something else, the synapse creation textbox just disappeared and the synapse was lost. I had to hit Enter to make the synapse stick with a blank description.

I want to propose having the synapses be created blank if you click away from synapse creation, rather than being lost.

@poietic @Connoropolous, is this something you guys think should be discouraged, and so it's a feature of the platform? If so, we could close this issue based on that idea.

Otherwise, I think it would really enhance my mapping to be able to make synapses more quickly.

TODO
- [x] Hear from others if they want this feature
- [x] Find the code that closes a synapse when you "click away", and have it run the submit handler so that the synapse is created.

**Comment by Connoropolous** [comment]
I definitely agree with the logic of this Devin

**Comment by poietic** [comment]
would there be a way to cancel synapse creation without having to click away for creation, then delete the synapse?

**Comment by devvmh** [comment]
I'm thinking ESC would be the best way. We can make sure that happens. If
you start dragging a synapse and never connect it to a topic, it cancels
the creation too, so we can also preserve that behavior

**Comment by poietic** [comment]
lets try it out on the staging area and see how it feels!

**Comment by Bortseb** [comment]
maybe clicking away only creates the synapse if it is currently blank? If
the user starts typing anything at all, it might still be best to require
enter to be pressed still... so that unfinished synapses, with some text
entered, aren't just created by accident if the user just happens to click
away. (Although, if this is the case, its not a huge deal... the user will
see the new synapse appear and should be away that they aren't finished
yet, and can fix it)

**Comment by devvmh** [comment]
ok this behaviour is pushed to auto-synapse-wip.

Rob, I thought about your comment but I went with the consistent approach for now (if you click the canvas and the new synapse form is visible, it creates a new synapse, whether it's blank or has text). I guess let's try it on staging once @Connoropolous  gets it up there! (It wouldn't be too hard to make it the way you suggest either).

https://github.com/metamaps/metamaps_gen002/compare/auto-synapse-wip

**Comment by Connoropolous** [comment]
I've left a comment on Devins branch for this, just needs a bit of revision
before I push it

**Comment by devvmh** [comment]
mmmm nevermind
I'm wrong.

Fixing it now

**Comment by devvmh** [comment]
I think this is better as a PR than an issue https://github.com/metamaps/metamaps_gen002/pull/447
