### ISSUE TITLE
Email auth details hardcoded

### ISSUE THREAD

**Issue by s01us** [metamaps/metamaps_gen002#405]
in your dev/ production env you have :

```ruby
 28     address:              'mail.metamaps.cc',
 29     port:                 587,
 30     user_name:            'team@metamaps.cc',
 31     password:             'RcxX+s:fht49UX',
 32     authentication:       'plain',
 33     enable_starttls_auto: true,
 34     openssl_verify_mode: 'none'   
```

I'm not sure if you've got security around that or if that's a slip up.
either way, might be nice to extract these out into ENV vars

**Comment by Connoropolous** [comment]
It's a security issue, we have known about it, planning to address it
extremely soon :) Thanks for bringing it to attention though!

**Comment by s01us** [comment]
:gift: https://github.com/metamaps/metamaps_gen002/pull/406
