### ISSUE TITLE
Metamaps installation (git cloning) ->Bundler no more included with rvm (as of march 31)

### ISSUE THREAD

**Issue by someone635** [metamaps/metamaps_gen002#410]
Hi metamaps,

I tried cloning the metamaps repository , but when running ./configure.sh, I ran in an error when the it tried to run 'bundle install', saying it could not find bundler (I didn't log the exact error name, sorry).

I found on this site:
http://railsapps.github.io/installrubyonrails-ubuntu.html    (Under "RVM' global gemset / Install bundler")

that, as of march 31th, 2015. rvm had stopped installing bundler automatically. Thus I did, right after the error:

    vagrant ssh
    gem install bundler #(a couple of times because it did not seem to work the first time).
    gem list bundler #(To ensure bundler was installed successfully)
    exit

And then ran again ./configure.sh

And the installation worked.

I tried modifying the Vagrantfile to add the 'gem install bundler' to the script, but it didn't seem to work (I'm a complete newbie in Web development so I surely did something wrong there), so maybe someone with more experience than me could add it in to the code and clean up the installation process.

This is my first contribution to Github, so if I did something wrong or something is unclear, please tell me.

Thanks.

**Comment by devvmh** [comment]
Hey that's great, thanks! What a helpful issue report. Very clear and perfectly done :D 

@Connoropolous I've fixed this on the master branch and pushed it. I haven't been keeping track of how develop and master have diverged.... should I be pushing to other branch(es) too?

**Comment by Connoropolous** [comment]
Nope, having it on master is good. Awesome all, cheers!
