### ISSUE TITLE
Issue with Socket.io frequently prevents me from mapping

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps_gen002#433]
The following is the error message given in the console:

http://metamaps.cc:5001/socket.io/1/?t=1446145643048 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

Basically,  everything is working fine... I am mapping, adding new topics etc... Then all of a sudden I try to double click to create a new topic  and it doesn't work anymore. This is when the above error shows up in the console...

It would be really great if this could get fixed, because I would love to more deeply implement metamapping into my daily routine while at work... but this pesky bug frequently breaks my flow, and I wind up not adding all my thoughts into a map. (and then move on assuming that I can't map anymore because its broken, and seems to stay broken)

I did a google search, and found the following,... but I don't have time now to read more in depth.
http://stackoverflow.com/questions/11653237/socket-io-failed-to-load-resource

**Comment by Connoropolous** [comment]
Didn't we already figure out that it's blocking that port from where you
work?
Not an issue with Metamaps exactly, but it would be good to resolve somehow

**Comment by devvmh** [comment]
@Bortseb  Could you post the section of application.js where this error happens? I know the code is uglified but a snippet or screenshot of the offending code could help. If we could narrow this down to a specific function, we could, say, lower the timeout, and/or make the code resilient to failures to socket.io

I'm sure if I knew the realtime code better I wouldn't need the reference, but regardless if you track it down maybe we can make the code less whiny.

**Comment by devvmh** [comment]
New brainwave I had today: get realtime.metamaps.cc as a domain name, and then use nginx to proxy the request over port 443 to the realtime server on port 5001. If a firewall has a problem with port 443, we're in trouble :D 

That means we can probably fix and close this this week!

**Comment by devvmh** [comment]
https://realtime.metamaps.cc is currently serving the socket.io server, but on my staging server I had troubles pointing the app to wss://realtime.devinhoward.ca (my tls-enabled staging socket.io server). I haven't tried with heroku yet.

Nginx proxying does take a bit of config, but it was on the web. Should I document that somewhere? Nah....

Hopefully this will be solved by the end of the rails 4 migration, but if it's too hard then it won't happen

**Comment by devvmh** [comment]
It's hard to test now that Rob doesn't have a corporate firewall, but I believe this issue is now fixed!
