### ISSUE TITLE
migrate InMetacodeSet table to be a HABTM association

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps_gen002#437]
Rails has "has and belongs to many" associations, which allow you to have a "join table" between two models. This could help cut down code related to the InMetacodeSet table.

In particular, we'd end up changing the in_metacode_sets table to a metacode_metacode_sets table, which would contain: id integer, metacode_id integer, metacode_set_id integer. Each entry in the table would mark a metacode as being in a set, and a set as having that metacode. Rails will understand this association well, and we won't need as much code to manage the relationship.

**Comment by Connoropolous** [comment]
let's do it

On Fri, Nov 6, 2015 at 11:15 AM, Devin Howard <notifications@github.com>
wrote:

> Rails has "has and belongs to many" associations, which allow you to have
> a "join table" between two models. This could help cut down code related to
> the InMetacodeSet table.
>
> In particular, we'd end up changing the in_metacode_sets table to a
> metacode_metacode_sets table, which would contain: id integer, metacode_id
> integer, metacode_set_id integer. Each entry in the table would mark a
> metacode as being in a set, and a set as having that metacode. Rails will
> understand this association well, and we won't need as much code to manage
> the relationship.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/437>.
>



-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by devvmh** [comment]
clearly i thrive on encouragement. This is fixed in 16c297574eca5a9f1b65ea3e9eedb40b51e1e186
