### ISSUE TITLE
Set metamaps up with ssl/https

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps_gen002#438]

**Comment by devvmh** [comment]
We should definitely try to join the beta of Let's Encrypt. I've been thinking about this separately. It'll be a few weeks until it's set up

Realistically we should enforce SSL to be good internet citizens

https://community.letsencrypt.org/t/beta-program-announcements/1631

**Comment by devvmh** [comment]
OK I submitted a beta request for let's encrypt; i'm not sure how long it takes to get it though, it may be a few months

**Comment by devvmh** [comment]
https://metamaps.cc is up and running. I want to wait until December 15 to close this ticket, so I can make sure the automated renewal is actually working (and probably wait before spreading the word widely - I'd rather not people get "untrusted certificate" errors if anything goes wrong

**Comment by devvmh** [comment]
Another question to answer is whether http://metamaps.cc should be redirected to SSL, or if it should remain a choice. The only reason to not do that is it might be slower? I'm not 100% sure of that. Probably some testing from different clients would be the best way to answer the question

**Comment by devvmh** [comment]
OK Metamaps is now served over https, but there are other problems outlined in https://github.com/metamaps/metamaps_gen002/issues/444
