### ISSUE TITLE
HTTPS problems

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps_gen002#444]
Modern browsers (particularly Chrome) freak out if you serve HTTP content on a page that's supposed to be secured. This means that currently if you access metamaps via https://metamaps.cc, it won't work. There are several issues to solve here.

Further, for realtime video to work in Chrome, metamaps MUST be served over HTTPS. So our hand is being forced a bit.

Here's what we need to do:

 - [x] Ensure all rails-internal assets are served over either https or "//", which will infer the protocol. Since we're moving long term to https-only (which is a good decision I think, even though it's a bit harder to support serverside), it's probably best to use https wherever possible (since we can serve https assets safely inside the http page. I can take this on, progress is in the https://github.com/metamaps/metamaps_gen002/tree/feature/https-preparation branch
 - [x] http://support.metamaps.cc/logout.json gives an error, but it's required in our page. @Connoropolous and/or @poietic do you have any insights? The answer may have to be changing the url to metamaps.uservoice.com, per [this page](http://feedback.uservoice.com/knowledgebase/articles/16819-site-settings-for-uservoice-product-management#forcessl).
 - [x] http://metamaps.cc:5001 gives an error. I suggest creating a CNAME called realtime.metamaps.cc, so we can change the javascript code to https://realtime.metamaps.cc (which will proxy to http://127.0.0.1:5001, so it'll end up being the exact same realtime server except using https).
 - [x] Ensure all user profile images are served over HTTPS, or they won't be visible. This is harder. This entails either enforcing https on the specified images, or using file uploads instead. I'm not 100% sure but it's possible these are already served via AWS, which has HTTPS so we're good. I'll check this out and make sure it's AWS or tag people to help me decide how to handle this. Used the s3_protocol configuration option on paperclip to fix map screenshots and presumably user profile images too.
 - [x] Ensure all custom metacode icons are served over HTTPS. Currently there are a lot hosted at dropbox (on staging); I'm not sure if these are HTTPS or not. Anyways, these ones we definitely need to change our strategy. I'm kind of annoyed by the UX issue of forcing users to use HTTPS icons only. Probably the best long term solution is to allow arbitrary URLs, but then grab them and upload them to AWS if they're HTTP. @Connoropolous @poietic @benb I welcome input on this.
 - [x] ~~Consider linking to ssl-enabled versions of blog.metamaps.cc and support.metamaps.cc. This isn't 100% required but I think it's a good idea? @poietic I'll need your help with the blog.metamaps.cc part of this, since I don't know how that's hosted. If you'd like, we could move this to the linode server on metamaps.cc, but if we can keep it on web hosting hub it means less work for me in the long run.~~
 - [x] Push the changes to the production server, but don't enforce SSL yet. Then we can do testing on https://metamaps.cc while still serving the content at http://metamaps.cc Once we're confident, we can start enforcing http. [EDIT: well, this isn't done, but it can be part of the rails4 push]

This ticket is a bit timely if we want real time video to work well when it launches.

**Comment by devvmh** [comment]
OK I checked on Metamaps.cc and I guess the users are uploaded by Paperclip, so they're good (I'm hoping). Metacodes on metamaps.cc specifically are also fine - there currently aren't any custom metacodes. This isn't true for some of the other instances (I'm guessing), but we can cross that bridge when we come to it. The dropbox metacode icons are on staging I guess.

So we still need to solve that Metacode issue, it's just not pressing for the realtime video release. I'll make a separate issue for it.

**Comment by devvmh** [comment]
I'm going to make a PR for my branch, but I don't think most problems are coming from rails-internal assets. We should be able to check that off fairly quickly.

**Comment by devvmh** [comment]
After some cursory testing at the current, buggy https://metamaps.cc, I've concluded that rails-internal assets are served fine, with the exception of the realtime server, so I'm checking off the first box above.

**Comment by devvmh** [comment]
Removing the points about support.metamaps.cc and blog.metamaps.cc over https. Let's not overcomplicate. The point about http://support.metamaps.cc/logout.json still stands though; it's still there.

**Comment by devvmh** [comment]
On the feature/https-preparation branch, I figured out how to get AWS S3 assets to come via https. Added a note to the top comment.

**Comment by Connoropolous** [comment]
excellent. @devvmh thanks so much for taking these things into consideration, as we prepare to be able to launch the video stuff, because you're absolutely right, it requires it. 

per " http://support.metamaps.cc/logout.json gives an error, but it's required in our page. The answer may have to be changing the url to metamaps.uservoice.com, per this page."
I believe that we've lost access to our advanced features of uservoice, which probably includes single-sign-on, @poietic can you confirm? if so, we can just take this line out of the code entirely for now, and look for a solution at the time if/when we need to.

**Comment by poietic** [comment]
Yes, we have lost single sign-on for uservoice :(

On Sun, Dec 20, 2015 at 9:53 AM, Connor Turland <notifications@github.com>
wrote:

> excellent. @devvmh <https://github.com/devvmh> thanks so much for taking
> these things into consideration, as we prepare to be able to launch the
> video stuff, because you're absolutely right, it requires it.
>
> per " http://support.metamaps.cc/logout.json gives an error, but it's
> required in our page. The answer may have to be changing the url to
> metamaps.uservoice.com, per this page."
> I believe that we've lost access to our advanced features of uservoice,
> which probably includes single-sign-on, @poietic
> <https://github.com/poietic> can you confirm? if so, we can just take
> this line out of the code entirely for now, and look for a solution at the
> time if/when we need to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/444#issuecomment-166140899>
> .
>



-- 
Ishan M. Shapiro
co-founder
Metamaps.cc <http://metamaps.cc/> | Notthisbody <http://notthisbody.com>
@metamapps <http://twitter.com/metamapps> | @notthisbody
<http://twitter.com/notthisbody>
<http://cargo.notthisbody.com>

**Comment by Connoropolous** [comment]
Ok, not ideal in the bigger picture, but @devvmh could you just take out the line that includes that logout.json file?

**Comment by devvmh** [comment]
OK I took the uservoice single sign on code out of the application.html.erb, and I'm merging the https-preparation pull request into develop

**Comment by devvmh** [comment]
OK, so this is done. We'll just need a brief window after either a "rails4" push or a "rails4 + realtime video" push to test out https, then we can enforce https. This is only important because I think we shouldn't announce realtime video until https is enforced, because of the Chrome issue with non-HTTPS video.
