### ISSUE TITLE
Metacode icons not at an HTTPS url won't work if Metamaps is served over https

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps_gen002#445]
### Game plan (made easier since metacode editing is only for admins):

- [x] Create a database migration that changes icon into an aws field
- [x] Make sure that metamaps.cc icons will be safely migration from a text field like "/assets/blueprints/bp_wildcard96px.png" to being a proper paperclip field
- [x] Metacode paperclip file upload UI instead of a text field
- [ ] ~~Migrate metamaps.cc~~
- [ ] ~~Ensure local dev instances and staging work OK~~
- [ ] ~~Ensure other instances are/will be migrated OK~~

(I'm happy closing this issue before we migrate every instance)

### OLD EXPLANATION:

Once we move to using https only, we'll have a UX issue.

If I want to create a new metacode set using images hosted at http://insecure.devinhoward.ca, which doesn't have SSL, I'll have a problem. I'll create the metacodes, and for the icon field I'll fill in a url like "http://insecure.devinhoward.ca/cool-metacode.png". But then Chrome and Opera and others will block that content, or worse, mark the entire page as insecure because there's an insecure image in the page for every page containing that metacode.

So possible solutions are:

1. Only allow the icon field to take urls starting with https
2. Change the field to an AWS file upload like user profile images [EDIT: going with this one]
3. Keep the field as a text field, but if it starts with http, use a script to download that image and then store it on AWS and serve it via HTTPS.

Here are the problems I've noticed for each approach:

1. This kind of sucks as as solution, because I might put https://insecure.devinhoward.ca/cool-metacode.png in the field, and then it won't be secure, so it'll create security errors.
2. Perhaps we didn't do this in the past because of copyright issues? I'm not sure. This seems like the best solution to me.
3. This is ambitious, lots of work, and still has problems. If a website starts out secure, but the certificate expires, we're screwed. I really wouldn't want to be tracking down these insecure images and fixing them later...

After reflecting on these three options, I've convinced myself the only way is to do it all via AWS and serve it over HTTPS, because that's really the only reliable way I see to ensure all metacode icons are secure forever. Do others have thoughts?

**Comment by Connoropolous** [comment]
@devvmh I like solution number 2. We'd need to write a small migration to change the schema of the metacodes table so that it could have a paperclip attachment image as well, and receive file uploads like the map screenshots and the profile image but I think that makes sense. 

It also makes administration of the metacodes on a per instance basis fairly easy, the image assets never have to be stored in with the code.

**Comment by devvmh** [comment]
This will be fine for metamaps.cc, but it'll totally screw up the staging database without a really complicated migration. I'll consider taking a look at migrating, but how bad would it be to wipe out the staging database and restart from fixtures?

**Comment by Connoropolous** [comment]
We shouldn't worry about staging really, we could just keep setting all the
metacodes to wildcard or whatever. There is actual content we'd prefer not
to lose in staging. Not much of it, but a bit.

**Comment by devvmh** [comment]
Acknowledged. We can also be less worried about ssl errors on staging, though it would be nice to get them cleaned up eventually

**Comment by devvmh** [comment]
progress on https://github.com/metamaps/metamaps_gen002/compare/feature/metacode-icon-on-aws

**Comment by devvmh** [comment]
@connor can you help me out? Can you load the feature/metacode-icon-on-aws branch and test it out on development?

I've got one big issue where it takes 5 minutes to load the metacode index, and then displays urls instead of images. I know how to fix that, but not the best way...

The other one is I don't know how to seed the database with S3 values. Or how to make it work in development. 

In the meantime, I'm taking a stab at making the images render and not take 5 minutes. I'm wondering if I just don't understand how S3/paperclip are supposed to work

**Comment by Connoropolous** [comment]
on it :)

**Comment by connor** [comment]
wrong @connor :)

**Comment by Connoropolous** [comment]
Sorry about that @connor :p

**Comment by Connoropolous** [comment]
@devvmh so I guess as part of this we could take the icon image assets out of the repo...

we could put them in a separate repo with a bit of separate documentation. they are licensed CC.
