### ISSUE TITLE
db migration issue on rails 4 upgrade

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps_gen002#452]
when migrating production db to rails 4, i get this error:

ActiveRecord::RecordNotFound: Couldn't find Synapse with 'id'=363
/usr/local/rvm/gems/ruby-2.1.3@metamaps_gen002/gems/activerecord-4.2.4/lib/active_record/core.rb:155:in `find'
/home/metamaps/metamaps_gen002/db/migrate/20151001024122_mapping_polymorphism.rb:18:in `block in up'

**Comment by Connoropolous** [comment]
Some kind of data integrity issue. Not sure beyond that. Did you have any
luck with it?

On Tuesday, January 5, 2016, Devin Howard <notifications@github.com> wrote:

> when migrating production db to rails 4, i get this error:
>
> ActiveRecord::RecordNotFound: Couldn't find Synapse with 'id'=363
> /usr/local/rvm/gems/ruby-213@metamaps_gen002/gems/activerecord-424/lib/active_record/corerb:155:in
> find'
>
> /home/metamaps/metamaps_gen002/db/migrate/20151001024122_mapping_polymorphismrb:18:inblock
> in up'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/452>.
>


-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by devvmh** [comment]
fixed by https://github.com/metamaps/metamaps_gen002/commit/75d9339010823cf6e2928eba502bdf41db38b125
