### ISSUE TITLE
Autocomplete broken again :(

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps_gen002#501]
I'll fix it. Just leaving this here for myself

**Comment by harlantwood** [comment]
This reminds me: are there tests for JS parts of the app, or just for the ruby parts?

**Comment by Connoropolous** [comment]
fixed in #87d6dfe

**Comment by devvmh** [comment]
@harlantwood There aren't any tests for Javascript

My current list of priorities for Metamaps is:

1) import/export
2) refactor Javascript into one-object-per-file (Metamaps.Global, Metamaps.Import, Metamaps.Create, etc)
3) Choose a JS testing framework, optionally integrate it with Rake (I've never done this before)
4) JS tests (although I'm actually more motivated about 2 & 3 than I am about this step - if the infrastructure is there we can build the tests incrementally like we're doing for the ruby code)
