### ISSUE TITLE
Production setup 

### ISSUE THREAD

**Issue by harlantwood** [metamaps/metamaps_gen002#518]
I'm considering setting up a production Metamaps instance, and wondering:

- do you have recommendations on where to host?  I'm thinking digital ocean for production, with assets on S3, and staging on heroku
- about how much do you pay per month for production hosting?  

Thanks!

**Comment by devvmh** [comment]
Thats essentially exactly our setup (with linode, not digital ocean). We're
on a 2GB RAM server, but when mm.cc was smaller it ran fine on 1GB.

Heroku actually doesnt do a very good job emulating our production
environment, particularly now that we have https I believe.  I've resorted
to hosting another staging instance on the production server to test some
features.

I have some documentation i could send you about my steps setting up a
production instance.  Maybe I'll just add it to the repo today

**Comment by harlantwood** [comment]
Thanks Devin!

**Comment by devvmh** [comment]
https://github.com/metamaps/metamaps_gen002/blob/feature/production-deploy-steps/doc/production/first-deploy.md
